services:
  mysql:
    image: mysql
    ports:
      - 3456:3306
    environment:
      MYSQL_ROOT_PASSWORD: VcXfUsOOjUhFJMlCIAjgdOaUiKJWrjUa
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: